server:
  port: 8080

logging:
  file:
    name: msoccurrence.log
    path: .

spring:
  config:
    activate:
      on-profile: docker
  application:
    name: msoccurrence
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DB_HOST}:${SPRING_DB_PORT}/${SPRING_DB_NAME}
    username: ${SPRING_DB_USER}
    password: ${SPRING_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: never

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# springdoc api configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api/docs.html
    operations-sorter: method

# Basic Security
access:
  username: ${SPRING_ACCESS_USERNAME}
  password: ${SPRING_ACCESS_PASSWORD}
  swagger: ${SPRING_ACCESS_HOST_SWAGGER}




