server:
  port: 8082

logging:
  file:
    name: msapplication.log
    path: .

spring:
  config:
    activate:
      on-profile: qa
  application:
    name: msapplication
  datasource:
    driver-class-name: org.postgresql.Driver
    username: <username>
    url: jdbc:postgresql://localhost:5432/bd
    password: <password>
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# springdoc api configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api/docs.html
    operations-sorter: method

access:
  username: PNMS
  password: PNQA#MS#23


notification:
  email:
    default-email-sender: ${DEFAULT_EMAIL_SENDER}
    default-origin: ${DEFAULT_EMAIL_ORIGIN}
  sms:
    default-origin: ${DEFAULT_SMS_ORIGIN}
    default-source: ${DEFAULT_SMS_SOURCE}